#!/bin/sh
. /usr/share/libubox/jshn.sh

case "$1" in
	list)
		echo '{ "set": { "username": "String", "password": "String" }}'
	;;
	call)
		case "$2" in
			set)
				# read the arguments
				read input;

				# optionally log the call

				logger -t "PASSWORD CHANGE" "call" "$2" "$input"
				json_load "$input"
				json_get_var new_password password
				json_get_var username username
				if [-z $username ] || [ -z $new_password ]; then
					echo '{ "success": false, "password": "NOT_SET"}'
				else
					(echo $new_password; sleep 1; echo $new_password) | passwd $username > /dev/null 2>&1;	
					#echo '{ "success": true, "username": "'$username'", "password": "REDACTED"}'
					#echo '{ "success": true, "username": "'$username'", "password": "'$new_password'"}'
				fi	
			;;
		esac
	;;
esac
